#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define OS_TOTAL_INTERRUPTS 256

#define OS_SECTOR_SIZE 512
#define OS_MAX_FILE 10

#define OS_EXTERN_FUNCTIONS 13

#define MAX_FILENAME_LENGTH 6

#endif